ebook_metadata:
  title: ༄༅། །ལེགས་བཤད་གསེར་གྱི་ཐུར་མ་ཞེས་བྱ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  sku: SHE-SHAP-19
  layers:
  - book_title
  - author
  - quotation
  - yigchung
web_metadata:
  title:
    en: The Golden Scalpel:An Excellent Discourse
    bo: ལེགས་བཤད་གསེར་གྱི་ཐུར་མ་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 19
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༡༩
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-19
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-19.epub
  description:
    en: ''
    bo: ''
